name: wheelwear_frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6

  camera: ^0.11.0+1 # 최신 버전 확인 후 업데이트
  #path_provider: ^2.0.15 # (사진 저장 시 필요)
  #permission_handler: ^11.0.1 # (카메라 권한 요청)

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
#  flutter_native_splash: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/auth/
    - assets/closet/
    - assets/config/.env

  uses-material-design: true

#flutter_native_splash:
#  color: "#FFFFFF"
#  image: assets/auth/splashLogo.png
#  android: true
#  ios: true
#  fullscreen: true
#  android_12:
#    color: "#FFFFFF"
#    image: assets/auth/splashLogo.png

