name: wheelwear_frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  dio: ^5.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.7

  camera: ^0.11.1 # 최신 버전 확인 후 업데이트
  camera_android: ^0.10.8+12
  flutter_exif_rotation: ^0.5.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
#  flutter_native_splash: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 2.4.5
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  assets:
    - assets/
    - assets/auth/
    - assets/closet/
    - assets/fitting/
    - assets/config/.env

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # 아이콘 이미지 경로
  adaptive_icon_background: "#ffffff"  # 안드로이드 적응형 아이콘 배경 (선택)
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/auth/splash.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/auth/splash.png

