# # Uncomment the next line to define a global platform for your project
# # platform :ios, '12.0'
#
# target 'Runner' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   # Pods for Runner
#
#   target 'RunnerTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
platform :ios, '18.3'  # iOS 버전 명시 (12.0보다 최신으로 설정 추천)

def flutter_root
  # Flutter 루트 경로를 동적으로 찾는 코드
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist."
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
